program: train.py
method: grid
metric:
  name: Test/Loss
  goal: minimize
parameters:
  lr: 
    values:
    - 0.1
    - 0.01
    - 0.001
    - 0.0001
  batch_size:
    values:
    - 32
    - 64
    - 128
    - 256
